In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.item()

7

In [5]:
scalar.ndim

0

In [7]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4151, 0.5744, 0.1226, 0.9227],
        [0.0462, 0.2972, 0.5587, 0.3582],
        [0.3181, 0.4530, 0.1327, 0.1586]])

In [8]:
random_tensor.dtype

torch.float32

In [11]:
torch.arange(start=1, end=10, step=2)

tensor([1, 3, 5, 7, 9])

In [13]:
zeros = torch.zeros_like(torch.arange(1, 10, 2))
zeros

tensor([0, 0, 0, 0, 0])

In [15]:
tensor = torch.tensor([3, 6, 9], dtype=torch.float32, device=None, requires_grad=False)

In [18]:
x = torch.arange(1, 100, 10)
torch.max(x.type(torch.float32))

tensor(91.)

In [19]:
torch.argmin(x)

tensor(0)

In [20]:
torch.stack([x, x, x], dim=0)

tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])

In [21]:
torch.squeeze(x)

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [26]:
torch.unsqueeze(torch.unsqueeze(x, dim=0), dim=2)

tensor([[[ 1],
         [11],
         [21],
         [31],
         [41],
         [51],
         [61],
         [71],
         [81],
         [91]]])

In [28]:
array = np.arange(1, 8)
tensor = torch.from_numpy(array)
array = tensor.numpy()

In [29]:
torch.manual_seed(1)

In [30]:
torch.cuda.is_available()

False

In [31]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [33]:
torch.cuda.device_count()

0

putting tensor on gpu

In [34]:
tensor = torch.tensor([1, 2, 3], device='cpu')
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [35]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

In [36]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)